### ISSUE TITLE
css file name are broken

### ISSUE THREAD

**Issue by zakiAzfar** [NitzanHen/agrippa#3]
When I generate a component in agrippa eg: `agrippa gen radio`  The files are generated as:-

+ Radio
  - `radio.tsx`
  - `radio .module.css` instead of `radio.module.css`
 
It is a minor bug but it need to be corrected

**Comment by NitzanHen** [comment]
Hi, thanks for reporting this bug!
I'll try and fix this ASAP.

**Comment by NitzanHen** [comment]
I seem to have fixed it; I accidentally had a space in a template string, which caused this bug. The bug is fixed on [v1.1.0-rc.2](https://github.com/NitzanHen/agrippa/releases/tag/v1.1.0-rc.2), and until v1.1.0 is officially released (should be in a few days) you can use this version by calling `npx agrippa@next gen <name> [options...]` (or installing `agrippa@next` globally).

Again, thanks for pointing out this awkward bug!

**Comment by zakiAzfar** [comment]
😊😊😊
