### ISSUE TITLE
More examples?

### ISSUE THREAD

**Issue by vfonic** [NitzanHen/agrippa#36]
I'd love to see some example usages. This would help me understand better how the tool works. The only other way right now is to go over the documentation to read each of the options and try it out.

I believe there could be some examples such as:

```sh
npx agrippa gen button --ts --styling css --export-type default --base-dir app/javascript/agrippa --flat
```

And then show the output:

Two files:
```
app/javascript/agrippa/Button.tsx
app/javascript/agrippa/button.module.css
```

```tsx
// app/javascript/agrippa/Button.tsx
import React from 'react';
import classes from './button.module.css';

export interface ButtonProps {}

const Button: React.VFC<ButtonProps> = () => {
	
	return (
		<div></div>
	);
};

export default Button;
```

**Comment by NitzanHen** [comment]
You're right! examples could be nice and would help people in getting to the Agrippa and its options.

I'll try to get some examples ready, hoping to get some done within the next couple of days. 

If you have any further ideas for examples, how to present them, etc. I'd love to hear them!

**Comment by vfonic** [comment]
Thanks @NitzanHen!

My suggestion would be to perhaps show an example or two for each of the config options so that users can see the difference between different config values.

For example:

```sh
npx agrippa gen button --ts
```

```tsx
export interface ButtonProps {}

export const Button: React.VFC<ButtonProps> = () => {
	
	return (
		<div></div>
	);
};
```

vs

```sh
npx agrippa gen button --ts false
```

```tsx
export const Button = () => {
	
	return (
		<div></div>
	);
};
```

**Comment by NitzanHen** [comment]
As you might've noticed, I haven't managed to get some good examples out yet. Sorry. 

For the time being, Agrippa has a decent end-to-end testing system, the tests of which can serve as examples. I'll make it more user friendly (add some readmes for them and put a proper link to it), so that they're at least somewhat convenient to use.

I'm planning a revamp of the docs (creating a website for Agrippa, essentially), but it'll be a while before that's out. Once it is though - there'll be much more examples (and a live playground, probably).

**Comment by NitzanHen** [comment]
Following up on my last comment, I've added a Readme to the test/integration directory explaining a bit about the structure, and linked to it from the main page. It's not a complete solution by any means, but I'm hoping it can still be of use for some people.

Either way, if you (or anyone else) have feedback or suggestions, I'd love to hear them.

Thanks again for reaching out!
