### ISSUE TITLE
Have option to use type instead of interfaces for component props

### ISSUE THREAD

**Issue by spiftire** [NitzanHen/agrippa#41]
I personally prefere to use `type` instead of `interface` when describing the props in typescript. I see agrippa defaults to using `interface`
It would be nice to have some sort of flag to decide which alternative to use.

**Comment by NitzanHen** [comment]
Fair enough! I'll try to get it done for v1.3.0

**Comment by NitzanHen** [comment]
Sadly, since this feature requires its own flag (which, in turn, requires updating the schema on [SchemaStore](https://github.com/SchemaStore/schemastore)) as well as other tasks, releasing this in v1.3.0 would delay the release by at least a few days. 

So it won't be included in v1.3.0, though I'll try to get a special version with this feature as soon as I can after the v1.3 release.

Sorry!

**Comment by NitzanHen** [comment]
Ok, it's implemented in version `1.4.0-alpha.1`. You can install it using `npm i -g agrippa@1.4.0-alpha.1`, please test it out!

The new flag is `tsPropsDeclaration` (`--ts-props-declaration` in the command line), and it can receive either `interface` (the default) or `type`; the corresponding Typescript structure is then used. Note that using this flag in a non-TS environment will raise an error.

It's technically an unstable version, but the tests I set up for the feature pass and it seems to behave smoothly. Either way, if you come across any bugs or have any other feedback, please reply here!

**Comment by spiftire** [comment]
Great work. I'll but it to the test during the next week

**Comment by spiftire** [comment]
Seems to work as expected. Great work. Keep it up 🚀

**Comment by NitzanHen** [comment]
Thanks!
Closing this issue, if you find any bugs please open another issue.

**Comment by NitzanHen** [comment]
Thanks!
Closing this issue, if you find any bugs please open another issue.

Thanks again for suggesting this.
